site_name: anyGPT
repo_url: https://github.com/miguelalonsojr/anyGPT
edit_uri: edit/main/docs
site_description: anyGPT is a general purpose library for training any type of GPT model.
site_author: Miguel Alonso Jr
copyright: copyright © 2023 Miguel Alonso Jr.
nav:
  - Home: index.md
  - Getting Started:
      - Installation: installation.md
      - Data Preparation: data-prep.md
      - Training: training.md
      - Inference: inference.md
      - Using the Microservice: microservice.md
  - API:
      - Settings: settings-api-documentation.md
      - Data: data-api-documentation.md
      - Environments: environments-api-documentation.md
      - Inference: inference-api-documentation.md
      - Models: models-api-documentation.md
      - Training: training-api-documentation.md
theme:
  name: material
  features:
    - content.code.copy
markdown_extensions:
  - markdown_include.include:
      base_path: docs
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
