name: Publish to Test

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
  build-test-publish-test:
    runs-on: ubuntu-latest
    environment: test
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-deps
      - run: pip install .
      - run: pytest
      - run: python -m build
      - run: twine check dist/*
      - run: twine upload -r testpypi dist/* -u __token__ -p ${{ secrets.PYPITEST }}