name: Build and Test

on: 
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
  build-n-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-deps
      - run: pip install .
      - run: pytest --cov=src